<?php
$form->prepare();
$form->setAttribute('action', $this->url('admin/default', array('controller' => 'type', 'action' => 'create')));
$form->setAttribute('method', 'post');
?>
<?php echo $this->form()->openTag($form) ?>
<dl>
	<?php foreach ($form as $element): ?>
		<dd><?php echo $this->formRow($element) ?></dd>
	<?php endforeach ?>
</dl>
<?php echo $this->form()->closeTag() ?>

<script type="text/javascript">
	var availableTags = <?php echo json_encode($types) ?>;
 
	jQuery("#parent").autocomplete({
		source: availableTags
	});
</script>