<?php
$form->prepare();
$form->setAttribute('action', $this->url('admin/default', $routeOptions));
$form->setAttribute('method', 'post');
?>
<?php echo $this->form()->openTag($form) ?>
<dl>
	<?php foreach ($form as $element): ?>
		<dd><?php echo $this->formRow($element) ?></dd>
	<?php endforeach ?>
</dl>
<?php echo $this->form()->closeTag() ?>

<script type="text/javascript">
	jQuery(document).ready(function(){
		jQuery(".select").chosen({allow_single_deselect: true});
	});
</script>