<?php
echo $this->headLink(array('rel' => 'shortcut icon', 'type' => '', 'href' => $this->basePath() . ''))
        ->prependStylesheet($this->basePath() . '/css/style_resource.css')
?>

<!-- Scripts -->
<?php
echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath() . '/js/jquery.columnfilters.js')
?>
<style type="text/css">

    table tr th {
        background-color: #d3DADE;
        padding: 3px;
    }
    table tr.rowb { background-color:#EAf2FD; }

    table tr.filterColumns td { padding:2px; }

    body { padding-bottom:150px; }


</style>
<?php
//$this->title('Hello');



?>
<div id="form_resurce">
    <h1>RooM List</h1>
	<a href="<?php echo $this->url('home/default',array('controller'=>'index','action'=>'addRoom')) ?>">Add RooM</a>
    <table class="table" id="filterTable1" cellspacing="0" cellpadding="0">
		
        <thead>
            <tr>
                <th>Name</th>
                <th>Quality</th>
                <th>Description</th>
                <th></th>
            </tr>

        </thead>
        <tfoot></tfoot>
        <tbody>
<?php
$i=1;

foreach ($rooms as $room) {
	
	echo '<tr>';
	if(! is_object($room->getBuilding())){
		echo '<td> ### -'.$room->getNumber().'</td>'	;
	}else{
		echo '<td>'.$room->getBuilding()->getName().'-'.$room->getNumber().'</td>'	;
	}
	if(is_object($room->getQuality())){
		echo '<td>'.$room->getQuality()->getType().'</td>';
	}else{
		echo '<td> ### '.'</td>';
	}
	
	echo '<td>'.$room->getDescription().'</td>';
//	echo '<td>'.'<a href="'.$this->url('home/default/edit', array('id' => $room->getId())).'">edit</a>'.'</td></tr>';
//	echo '<td><input type="button" name="Book" value="Book"></td></tr>';
	$i++;
}
?>
           
        </tbody>
    </table>
</div>
<script>
    jQuery(document).ready(function() {
        jQuery('table#filterTable1').columnFilters({alternateRowClassNames:['rowa','rowb']});
        jQuery('table#filterTable2').columnFilters({alternateRowClassNames:['rowa','rowb'], excludeColumns:[2,3]});
        jQuery('table#filterTable3').columnFilters({caseSensitive:true});
        jQuery('table#filterTable4').columnFilters({minSearchCharacters:3});
        jQuery('table#filterTable5').columnFilters({wildCard:'#',notCharacter:'?'});
    });
</script>
</html>

