<?php
$form->prepare();
$form->setAttribute('action', $this->url('admin/default', array('controller' => 'item', 'action' => 'edit', 'uid' => $uid)));
$form->setAttribute('method', 'post');
?>
<?php echo $this->form()->openTag($form) ?>
<dl>
	<?php foreach ($form as $element): ?>
		<dd><?php echo $this->formRow($element) ?></dd>
	<?php endforeach ?>
</dl>
<?php echo $this->form()->closeTag() ?>

<script type="text/javascript">
	jQuery("#type").typeahead({
		source: <?php echo json_encode($types) ?>
	});
	jQuery("#parent").typeahead({
		source: <?php echo json_encode($items) ?>
	});
</script>