<?php if (count($messages)) : ?>
	<?php foreach ($messages as $msg) : ?>
		<?php echo $msg; ?>
	<?php endforeach; ?>
<?php endif; ?>

<form onsubmit="return checkValue();" method="post" action="<?php echo $this->url('admin/default', array('controller' => 'item', 'action' => 'new')); ?>">
	<input type="submit" class="btn" value="Create new"/>
	<select name="type" id="typeOfItem" class="select">
		<?php
		foreach ($types as $uid => $title) {
			echo '<option value="' . $uid . '">' . $title . '</option>';
		}
		?>
	</select>
</form>

<script type="text/javascript">
	function checkValue(){
		if(0 == jQuery('#typeOfItem').val()){
			return false;
		}
		return true;
	}
	jQuery(document).ready(function(){
		jQuery(".select").chosen({allow_single_deselect: true});
	});
</script>