<?php
$form->prepare();
$form->setAttribute('action', $this->url('manage/room', array('room'=>$roomId, 'building' => $buildingName, 'action' => 'edit')));
$form->setAttribute('method', 'post');
?>
<?php echo $this->form()->openTag($form) ?>
<dl>
	<?php foreach ($form as $element): ?>
		<dd><?php echo $this->formRow($element) ?></dd>
	<?php endforeach ?>
</dl>
<?php echo $this->form()->closeTag() ?>