<?php if (count($messages)) : ?>
	<?php foreach ($messages as $msg) : ?>
		<?php echo $msg; ?>
	<?php endforeach; ?>
<?php endif; ?>

<?php

foreach ($buildings as $building) {
	echo '<div class="well">';
	echo '<p>Building : ' . $building->getName() . '</p>';
	echo '<p>' . $building->getDescription() . '</p>';
	echo '<a href="' . $this->url('manage/room', array('action' => 'create', 'building'=>$building->getName())) . '">Add room</a>';
	echo '</div>';
}
?>

<?php echo $this->paginationControl($buildings, 'Sliding', 'resource-ms/building/pagination-building-list.phtml'); ?>