<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('' . $this->translate(''))->setSeparator(' - ')->setAutoEscape(true) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                ->prependStylesheet($this->basePath() . '/css/style.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                ->prependStylesheet($this->basePath() . '/css/style_home.css')
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                ->prependFile($this->basePath() . '/js/jquery.min.js')
        ?>

    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <?php /*    <img class="itc" src="<?php echo $this->basePath().'/images/ITC LOGO.gif';?>" > 
                      <img  class="gic" src="<?php echo $this->basePath().'images/New GIC-Logo.jpg';?>" >
                      <div class="picturemenu"><h1>Room Management System	</h1> */ ?>
                </div>
                <a class="brand" href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Skeleton Application') ?></a>
                <div class="nav-collapse collapse">
                    <ul class="nav">
                        <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                        <li class="active"><a href="<?php echo $this->url('users-list') ?>"><?php echo $this->translate('Users') ?></a></li>
                        <li class="active"><a href="<?php echo $this->url('booking') ?>"><?php echo $this->translate('Booking') ?></a></li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </div>



        <div class="container">
            <div class= "row">
                <div class="span2">
                    <div class="span2 bs-docs-sidebar">
                        <ul class="nav">
                            <li class="active"><a href="<?php echo $this->url('home') ?>"> Home </a> </li>
                            <li class="active"><a href="<?php echo $this->url('zfcuser/register') ?>"> Register  </a> </li>
                            <li class="active"><a href="<?php echo $this->url('zfcadmin/zfcuseradmin/list') ?>"> Users </a> </li>
                            <li class="active"><a href="<?php echo $this->url('home/rooms-list') ?>"> Resource </a></li> 
                            <li class="active"><a href="<?php echo $this->url('home/rooms-list') ?>"> Profile </a></li>
                            <li class="active"><a href="<?php echo $this->url('home/rooms-list') ?>"> About </a></li>
                            <li class="active"><a href="<?php echo $this->url('zfcuser/login') ?>"> Login </a></li>
                            <li class="active"><a href="<?php echo $this->url('zfcuser/logout') ?>"> Logout </a></li>
                        </ul>
                    </div>
                </div>
                <div class="span10">
                    <?php echo $this->content; ?>
                </div>
            </div>
        </div>
        <div>

            <hr>
            <footer>
                <p>&copy; 2012 by GIC Departement. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
