<a class="btn" href="<?php echo $this->url('home') ?>">Continue booking</a>

<br /><br />

<?php
foreach ($items as $typeTitle => $itemsArray) {
	echo $typeTitle . '<br />';
	foreach ($itemsArray as $item) {
		echo $item->getTitle() . ' ';
	}
	echo '<br />';
}
?>

<br /><br />

<form method="POST" action="<?php echo $this->url('home/default', array('controller' => 'reservation', 'action' => 'done')) ?>">
	<input name="submit" class="btn btn-success" type="submit" value="Done" />
</form>
