<?php echo $message ?>
<?php
$form->prepare();
$form->setAttribute('action', $this->url('home/default', array('controller' => 'reservation', 'action' => 'start')));
$form->setAttribute('method', 'post');
?>
<?php echo $this->form()->openTag($form) ?>
<dl>
	<?php foreach ($form as $element): ?>
		<dd><?php echo $this->formRow($element) ?></dd>
	<?php endforeach ?>
</dl>
<?php echo $this->form()->closeTag() ?>

<script type="text/javascript">
	$('.date').datepicker({
		
	});
</script>