<ul class="nav nav-list bs-docs-sidenav">
	<li><a href="<?php echo $this->url('home') ?>">Home</a></li>
	<li><a href="<?php echo $this->url('admin/default', array('controller' => 'type')) ?>">Type</a></li>
	<li><a href="<?php echo $this->url('admin/default', array('controller' => 'item','action'=>'list')) ?>">Item</a></li>
	<li><a href="<?php echo $this->url('zfcuser/login') ?>">Login</a></li>
</ul>