<ul class="nav nav-list bs-docs-sidenav">
	<li><a href="<?php echo $this->url('home') ?>">Booking</a></li>
	<li><a href="<?php echo $this->url('admin/default', array('controller' => 'type')) ?>">Type</a></li>
	<li><a href="<?php echo $this->url('admin/default', array('controller' => 'item','action'=>'list')) ?>">Resource</a></li>
	<li><a href="<?php echo $this->url('zfcadmin/zfcuseradmin/list') ?>">User management</a></li>
	<li><a href="<?php echo $this->url('zfcuser/login') ?>">Login</a></li>
</ul>