<a class="btn" 
   href="<?php echo $this->url('home/default', array('controller' => 'reservation', 'action' => 'start')); ?>">
	START RESERVATION
</a>

<?php
if ($reservationStarted) {
	echo '(start : ' . date('d/m/Y H:i', $start);
	echo ' end : ' . date('d/m/Y H:i', $end) . ')';
}
?>

<br /><br />

<table class="table table-bordered">
	<thead>
		<tr>
			<th>Title</th>
			<th>Type</th>
			<th>Quality</th>
			<?php if ($reservationStarted) { ?>
				<th></th>
			<?php } ?>
		</tr>
	</thead>
	<tbody>
		<?php
		foreach ($items as $item) {
			if (!$item->getIsBookable()) {
				continue;
			}

			echo '<tr>';
			echo '<td>' . $item->getTitle() . '</td>';
			if (NULL !== $item->getType()) {
				echo '<td>' . $item->getType()->getTitle() . '</td>';
			} else {
				echo '<td></td>';
			}

			$barType = 'bar-success';

			if ($item->getQuality() > 70) {
				$barType = 'bar-success';
			} else if ($item->getQuality() > 40) {
				$barType = 'bar-warning';
			} else if ($item->getQuality() > 0) {
				$barType = 'bar-danger';
			}

			echo '<td>
					<div class="progress progress-striped">
						<div class="bar ' . $barType . '" style="width: ' . $item->getQuality() . '%;"></div>
					</div>
				</td>';


			if ($reservationStarted) {
				echo '<td>';
				echo '<button value="' . $item->getUid() . '" class="btn bookButton" href="#">Book</button>';
				echo '</td>';
			}


			echo '</tr>';
		}
		?>
	</tbody>
</table>

<?php if ($reservationStarted) { ?>
	<button id="clearItems" class="btn">Clear</button>
	<button class="btn bookButton" value="0">View Items</button>
	<a class="btn" href="<?php echo $this->url('home/default', array('controller' => 'reservation', 'action' => 'done')); ?>">Finish</a>
<?php } ?>
<br /><br />

<div id="items">

</div>

<script type="text/javascript">
	jQuery(document).ready(function(){
		jQuery('.bookButton').click(function(){
			var itemUid = jQuery(this).val();
			
			jQuery.ajax({
				url: "<?php echo $this->url('home/default', array('controller' => 'reservation', 'action' => 'book')) ?>",
				type: "POST",
				data: {"itemUid": itemUid},
				complete: function(){
					
				},
				success: function(data){
					jQuery('#items').html(data);
				}
			});
			
		});
		jQuery('#clearItems').click(function(){
			jQuery.ajax({
				url: "<?php echo $this->url('home/default', array('controller' => 'reservation', 'action' => 'clear')) ?>",
				success: function(data){
					jQuery('#items').html(data);
				}
			});
		});
	});
</script>